name: tropico
description: QR meni za Caffe & Lounge Tropico
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts:
  firebase_core:
  cloud_firestore:
  lottie:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/pozadina.jpg
    - assets/icon.png
    - assets/logo.png
    - assets/toplapica.png
    - assets/bezalk.jpg
    - assets/prir.jpeg
    - assets/alk.jpg
    - assets/pivo.jpg
    - assets/lula.jpg
    - assets/kafa.json
    - assets/pozadine/topla.jpg
    - assets/pozadine/gazirana.jpeg
    - assets/pozadine/negazirana.jpeg
    - assets/pozadine/alkoholna.jpeg
    - assets/pozadine/pivo.jpeg
  uses-material-design: true
