// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv0dOlds_XoDPoxP-O4UkCN5ji3rD6Ri4',
    appId: '1:1001150861090:web:57f4513cbb20c72f7f5f7b',
    messagingSenderId: '1001150861090',
    projectId: 'caffetropico-33ab3',
    authDomain: 'caffetropico-33ab3.firebaseapp.com',
    storageBucket: 'caffetropico-33ab3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVcRybOP-KrLAE1U6V67uGMMq-luhCdEE',
    appId: '1:1001150861090:android:9c53c6850d9739107f5f7b',
    messagingSenderId: '1001150861090',
    projectId: 'caffetropico-33ab3',
    storageBucket: 'caffetropico-33ab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiXSOYpRySqNQl3kH4RNNkKSdSJH6L7CQ',
    appId: '1:1001150861090:ios:4380eb09241bab5c7f5f7b',
    messagingSenderId: '1001150861090',
    projectId: 'caffetropico-33ab3',
    storageBucket: 'caffetropico-33ab3.appspot.com',
    iosBundleId: 'com.example.tropico',
  );
}
