// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkOZJYqDcuYwEuooAyqDmseQXm_UvjxFU',
    appId: '1:213695105815:web:5034cccfe0c9d7839a0552',
    messagingSenderId: '213695105815',
    projectId: 'scanbrew-a47dc',
    authDomain: 'scanbrew-a47dc.firebaseapp.com',
    storageBucket: 'scanbrew-a47dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtFgcSugPb0sBrkka_Q8oCXBoyHRujWaE',
    appId: '1:213695105815:android:1f5aeac427912e1e9a0552',
    messagingSenderId: '213695105815',
    projectId: 'scanbrew-a47dc',
    storageBucket: 'scanbrew-a47dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGuELnloWWDh3LPqTEE0k305fQKjCE0lI',
    appId: '1:213695105815:ios:897c91b85dd9f8b19a0552',
    messagingSenderId: '213695105815',
    projectId: 'scanbrew-a47dc',
    storageBucket: 'scanbrew-a47dc.appspot.com',
    iosBundleId: 'com.example.tropico',
  );
}
